module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        background: 'var(--color-background)',
        text: 'var(--color-text)',
        'light-gray': 'var(--color-lightGray)',
        'medium-gray': 'var(--color-mediumGray)',
        'dark-gray': 'var(--color-darkGray)',
        zeta: {
          white: '#FFFFFF',
          gray: {
            50: '#F9FAFB',
            100: '#F3F4F6',
            200: '#E5E7EB',
            300: '#D1D5DB',
            400: '#9CA3AF',
            500: '#6B7280',
            600: '#4B5563',
            700: '#374151',
            800: '#1F2937',
            900: '#111827'
          }
        }
      },      boxShadow: {
        DEFAULT: 'var(--color-shadow)',
      },
      scale: {
        '102': '1.02',
        '105': '1.05',
      },
      fontFamily: {
        'typography-title': 'var(--typography-title-fontFamily)',
        'typography-heading': 'var(--typography-heading-fontFamily)',
        'typography-subheading': 'var(--typography-subheading-fontFamily)',
        'typography-description': 'var(--typography-description-fontFamily)',
        'typography-label': 'var(--typography-label-fontFamily)',
        'typography-body': 'var(--typography-body-fontFamily)',
        'typography-caption': 'var(--typography-caption-fontFamily)',
        'typography-button': 'var(--typography-button-fontFamily)',
        'typography-tooltip': 'var(--typography-tooltip-fontFamily)',
        'typography-code': 'var(--typography-code-fontFamily)',
      },
      fontSize: {
        'typography-title': 'var(--typography-title-fontSize)',
        'typography-heading': 'var(--typography-heading-fontSize)',
        'typography-subheading': 'var(--typography-subheading-fontSize)',
        'typography-description': 'var(--typography-description-fontSize)',
        'typography-label': 'var(--typography-label-fontSize)',
        'typography-body': 'var(--typography-body-fontSize)',
        'typography-caption': 'var(--typography-caption-fontSize)',
        'typography-button': 'var(--typography-button-fontSize)',
        'typography-tooltip': 'var(--typography-tooltip-fontSize)',
        'typography-code': 'var(--typography-code-fontSize)',
      },
      fontWeight: {
        'typography-title': 'var(--typography-title-fontWeight)',
        'typography-heading': 'var(--typography-heading-fontWeight)',
        'typography-subheading': 'var(--typography-subheading-fontWeight)',
        'typography-description': 'var(--typography-description-fontWeight)',
        'typography-label': 'var(--typography-label-fontWeight)',
        'typography-body': 'var(--typography-body-fontWeight)',
        'typography-caption': 'var(--typography-caption-fontWeight)',
        'typography-button': 'var(--typography-button-fontWeight)',
        'typography-tooltip': 'var(--typography-tooltip-fontWeight)',
        'typography-code': 'var(--typography-code-fontWeight)',
      },
      lineHeight: {
        'typography-title': 'var(--typography-title-lineHeight)',
        'typography-heading': 'var(--typography-heading-lineHeight)',
        'typography-subheading': 'var(--typography-subheading-lineHeight)',
        'typography-description': 'var(--typography-description-lineHeight)',
        'typography-label': 'var(--typography-label-lineHeight)',
        'typography-body': 'var(--typography-body-lineHeight)',
        'typography-caption': 'var(--typography-caption-lineHeight)',
        'typography-button': 'var(--typography-button-lineHeight)',
        'typography-tooltip': 'var(--typography-tooltip-lineHeight)',
        'typography-code': 'var(--typography-code-lineHeight)',
      },
      letterSpacing: {
        'typography-title': 'var(--typography-title-letterSpacing)',
        'typography-heading': 'var(--typography-heading-letterSpacing)',
        'typography-subheading': 'var(--typography-subheading-letterSpacing)',
        'typography-description': 'var(--typography-description-letterSpacing)',
        'typography-label': 'var(--typography-label-letterSpacing)',
        'typography-body': 'var(--typography-body-letterSpacing)',
        'typography-caption': 'var(--typography-caption-letterSpacing)',
        'typography-button': 'var(--typography-button-letterSpacing)',
        'typography-tooltip': 'var(--typography-tooltip-letterSpacing)',
        'typography-code': 'var(--typography-code-letterSpacing)',
      },
    },
  },
  plugins: [],
}